server:
  port: 9999

spring:
  application:
    name: gateway-service
  main:
    config:
      allow-override: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      enabled: true      #默认开启网关
      discovery:
        locator:
          enabled: false       #默认是不允许暴露微服务名称来进行路由匹配
      routes:
        - id: goods-route
          uri: lb://goods-service    #怎么实现的呢？  使用的是LoadBalancerClientFilter来实现
          predicates:
            - Path=/goods/**,/brand/**
        - id: file-route
          uri: lb://file-service    #怎么实现的呢？  使用的是LoadBalancerClientFilter来实现
          predicates:
            - Path=/fastdfs/**
          filters:
            - name: RequestRateLimiter
              args:
                key‐resolver: "#{@keyResolver}"   # SpEL表达式
                redis‐rate‐limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis‐rate‐limiter.burstCapacity: 1 #令牌桶总容量
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - TRACE
  redis:
    port: 6379
    host: 192.168.199.134
